### ISSUE TITLE
Upgrade League container to 2.0

### ISSUE THREAD

**Issue by sagikazarmark** [fuelphp/dependency#19]
Although I haven't looked at the changes yet, I am eager to update League container to version 2.x. Since fuel 2 is not RC yet, I believe we are allowed to do breaking changes.

Any objections?

**Comment by WanWizard** [comment]
Not from me.

**Comment by stevewest** [comment]
None here either.

**Comment by stevewest** [comment]
Working on this now, need this for conflicting packages elsewhere.

**Comment by ghost** [comment]
It broke a lot of things here, and I am working to fix them.
However, I understand its not RC.  Somehow I will get it all done.

(There hasn't been much in the way of transition guides from either League or FuelPHP).

**Comment by ghost** [comment]
The League/Container changelog is pretty much useless.

Before, the constructor accepted a configuration array.  Now I have no clue how to configure it using the array.  I wish someone somewhere would have wrote a transition guide.  Now I have to approach this like I'm using a completely new container package. If that is the case, maybe I want something more stable...
